"""Initial migration

Revision ID: a12fbe7b76d8
Revises: 
Create Date: 2025-05-14 07:51:09.252784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a12fbe7b76d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups',
    sa.Column('startup_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('headquarters', sa.String(length=255), nullable=False),
    sa.Column('total_funding', sa.String(length=50), nullable=False),
    sa.Column('valuation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('startup_id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('notifications')
    op.drop_table('Acquisitions')
    op.drop_table('funds')
    op.drop_table('StartupInvestors')
    op.drop_table('Founders')
    op.drop_table('FundingSources')
    with op.batch_alter_table('Startups', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('Startups')
    op.drop_table('EquityDetails')
    op.drop_table('audit_log')
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('expense_categories')
    op.drop_table('reports')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('setting_key')

    op.drop_table('system_settings')
    op.drop_table('StartupValuations')
    op.drop_table('expenses')
    op.drop_table('budgets')
    op.drop_table('ExitStrategies')
    with op.batch_alter_table('FundingRounds', schema=None) as batch_op:
        batch_op.drop_constraint('fundingrounds_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'startups', ['startup_id'], ['startup_id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('last_login')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_login', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('phone')
        batch_op.drop_column('username')

    with op.batch_alter_table('FundingRounds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fundingrounds_ibfk_1', 'Startups', ['startup_id'], ['startup_id'], ondelete='CASCADE')

    op.create_table('ExitStrategies',
    sa.Column('exit_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startup_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exit_type', mysql.ENUM('Acquisition', 'IPO', 'Merger', 'Shutdown'), nullable=True),
    sa.Column('exit_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['Startups.startup_id'], name='exitstrategies_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exit_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('budgets',
    sa.Column('budget_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('period', mysql.ENUM('Monthly', 'Quarterly', 'Yearly', 'Custom'), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('(`end_date` > `start_date`)', name='budgets_chk_1'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.category_id'], name='budgets_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='budgets_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('budget_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('expenses',
    sa.Column('expense_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('vendor', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('receipt_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.category_id'], name='expenses_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='expenses_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('expense_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('StartupValuations',
    sa.Column('valuation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startup_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valuation', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('valuation_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['Startups.startup_id'], name='startupvaluations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('valuation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('system_settings',
    sa.Column('setting_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('setting_value', mysql.TEXT(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('setting_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('setting_key', ['setting_key'], unique=True)

    op.create_table('reports',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.ENUM('Monthly', 'Quarterly', 'Annual', 'Custom', 'Investor'), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='reports_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('expense_categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('color_code', mysql.VARCHAR(length=7), server_default=sa.text("'#6c757d'"), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('audit_log',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('record_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_values', mysql.JSON(), nullable=True),
    sa.Column('new_values', mysql.JSON(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='audit_log_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('EquityDetails',
    sa.Column('equity_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('investor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('startup_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equity_percentage', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['Investors.investor_id'], name='equitydetails_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['Startups.startup_id'], name='equitydetails_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equity_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Startups',
    sa.Column('startup_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('industry', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('founded_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('headquarters', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_funding', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('valuation', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.PrimaryKeyConstraint('startup_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Startups', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('FundingSources',
    sa.Column('source_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('funding_round_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('investor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contribution', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['funding_round_id'], ['FundingRounds.round_id'], name='fundingsources_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['Investors.investor_id'], name='fundingsources_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Founders',
    sa.Column('founder_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startup_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['Startups.startup_id'], name='founders_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('founder_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('StartupInvestors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startup_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('investor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('investment_amount', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['Investors.investor_id'], name='startupinvestors_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['Startups.startup_id'], name='startupinvestors_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('funds',
    sa.Column('fund_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('funding_round', mysql.ENUM('Seed', 'Series A', 'Series B', 'Series C', 'IPO', 'Other'), nullable=False),
    sa.Column('date_received', sa.DATE(), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('attachment_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='funds_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('fund_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Acquisitions',
    sa.Column('acquisition_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acquired_startup_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acquirer_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('acquisition_price', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('acquisition_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['acquired_startup_id'], ['Startups.startup_id'], name='acquisitions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('acquisition_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='notifications_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('startups')
    # ### end Alembic commands ###
